# Generated by Django 4.2.6 on 2023-10-19 11:45

import contact_mgt_models_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to=contact_mgt_models_app.models.user_directory_path)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
